# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.IntegerField(choices=[(1, b'Comedy'), (2, b'Fantasy'), (3, b'Action'), (4, b'Romance'), (5, b'Adventure'), (6, b'Mystery'), (7, b'Horror')])),
            ],
        ),
    ]
